return {
  { import = "plugins.colorscheme" },
  { import = "plugins.lspconfig" },
  { import = "plugins.blink" },
  { import = "plugins.nvim-tree" },
  { import = "plugins.treesitter" },
  { import = "plugins.telescope" },
  { import = "plugins.which-key" },
  { import = "plugins.lualine" },
  { import = "plugins.mason" },
  { import = "plugins.mason-lspconfig" },
  { import = "plugins.bufferline" },
  { import = "plugins.indent-blankline" },
  { import = "plugins.gitsigns" },
  { import = "plugins.neoscroll" },
  { import = "plugins.autopairs" },
  { import = "plugins.mini-comment" },
  { import = "plugins.mini-surround" },
}
